version: '3'
services:
  acc_service_cnt:
    container_name: acc_service_cnt
    image: acc_service:latest
    restart: always
    links:
    - acc_database_cnt:data
    networks:
      lan:
        ipv4_address: 172.16.5.2
  acc_server_cnt:
    container_name: acc_server_cnt
    image: acc_server:latest
    restart: always
    links:
    - acc_database_cnt:data
    ports: ['8888:8080']
    networks:
      lan:
        ipv4_address: 172.16.5.3
  acc_database_cnt:
    container_name: acc_database_cnt
    image: acc_database:latest
    restart: always
    networks:
      lan:
        ipv4_address: 172.16.5.4
networks:
  lan:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.5.0/28
    driver_opts:
      com.docker.network.bridge.name: "br-acc"